name: Build & Release FastGrade App

on:
  push:
    tags:
      - 'v*'   # only run when pushing tags like v1.0.0

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build app (electron-builder will detect tag and version)
      - name: Build distributables
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}   # gives electron-builder permission to publish

      # 5. Upload release artifacts
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
